### ISSUE TITLE
Pytorch version

### ISSUE THREAD

**Issue by sixin-zh** [proximal-dg/proximal_dg#2]
Hello, which version of pytorch should be used to run the code? I did not find any documentation on this.

**Comment by sahilsid** [comment]
Hi @sixin-zh, any _torch>=1.2_ can be used to run the code, just like [torchgan](https://github.com/torchgan/torchgan).

**Comment by sixin-zh** [comment]
Hi, I just tried 1.9.0 and it works. Thank you!
